

(defpackage :macintosh
  (:use cl system flavors #+ticl ticl)
  ;; (:import make-mac)
  (:shadowing-import-from flavors make-instance defmethod)
  (:nicknames :mac :mac-windows ))

(defpackage :tv
  (:use cl flavors zeta-lisp-compatability)
  (:shadowing-import-from zeta-lisp-compatability defstruct)
  (:shadowing-import-from flavors make-instance defmethod)
  (:export
   standard-screen
   sheet-window-id
   mac-explorer-window-id
   *cold-load-streams-screen-selected-p*
   *default-mac-window-height*
   *default-mac-window-width*
   *dont-clip-at-the-margins*
   *explorer-to-mac-char-code-map*
   *ignore-commands-for-the-mac*
   *mac*
   *mac-keyboard-p*
   *mac-system-p*
   ;; dab 8/24/88
   *mac-resident-explorer-screens*
   ;; dab 8/24/88
   *undisplaced-mac-window-arrays*
   *window-system-mouse-on-the-mac*
   ;; dab 08-24-88 dab
   dump-draw-char-cache
   lispm-shift-bit
   lispm-greek-bit
   lispm-top-bit
   lispm-capslock-bit
   lispm-control-bit
   lispm-meta-bit
   lispm-super-bit
   lispm-hyper-bit
   lispm-altlock-bit
   lispm-modelock-bit
   lispm-repeat-bit

   mac-control-bit
   mac-option-bit
   mac-capslock-bit
   mac-shift-bit
   mac-command-bit
   mac-mouse-bit
   mac-autokey-bit
   mac-window-activate-bit
   ;; dab 8/24/88
   mac-explorer-screen-id-for-screen-being-created
   mac-extended-kbd-descriptor
   mac-kbd-modifier-table
   mac-kbd-modifier-table-zmacs-mode
   mac-screen
   ;; dab 8/24/88
   mac-screen-for-printer
   mac-standard-kbd-descriptor
   ;; dab 8/24/88
   not-visible-p
   kbd-mac-table

   ;; functions
   activate-mac-window
   after-tv-initialized
   analyze-last-button
   deactivate-mac-screen
   deactivate-mac-window
   define-mac-resident-exp-screen
   deselect-cold-load-streams-screen
   give-mouse-ownership-to-the-explorer
   kbd-convert-mac
   kbd-make-mac-table
   lispm-or-mac-mouse-wakeup
   mac-consider-mouse
   mac-key
   mac-screen-p
   mac-system-p
   mac-window-p
   make-a-mac-resident-explorer-screen
   ;; dab 8/24/88
   make-explorer-screen
   redirect-drawing-of-window-and-inferiors
   ;; 10/18/88
   remember-bit-array
   remember-this-screens-last-selected-window
   select-cold-load-streams-screen
   send-adjust-bit-array-maybe
   send-draw-char
   send-draw-line
   send-draw-point
   send-draw-rectangle
   send-draw-string
   send-drawcircle
   send-drawhollowcircle
   send-drawhollowrectangle
   send-draw-filled-polygon
   send-select-window
   select-a-screen
   si-bitblt
   window))

;; The following symbols are those which are intended to be
;; documented. They are suitable for exporting from the W package, the
;; successor to TV.
(defpackage :w
  (:use  cl tv ticl system)
  (:export *bidirectional-more-standard-message*
	   *default-background*
	   *default-foreground*
	   *default-border-color*		;new for color
	   *default-scroll-bar-color*
	   *deselected-process-priority*
	   *enable-typeout-window-borders*
	   *hollow-m-choice-box-p*
	   *mouse-incrementing-keystates*
	   *scroll-bar-char-index*
	   *scroll-bar-char-x-offset*
	   *scroll-bar-char-y-offset*
	   *scroll-bar-default-clicks*
	   *scroll-bar-default-delay-time*
	   *scroll-bar-default-icon-height*
	   *scroll-bar-default-icon-width*
	   *scroll-bar-default-lines*
	   *scroll-bar-default-mode*
	   *scroll-bar-default-side*
	   *scroll-bar-shade*
	   *scroll-bar-who-line-documentation*
	   *selected-process-priority*
	   *system-keys*
	   *terminal-keys*
	   *unexpected-select-delay*
	   100%-black
	   100%-white
	   12%-gray
	   12-hour-clock-setup
	   24-hour-clock-setup
	   25%-gray
	   33%-gray
	   50%-gray
	   66%-gray
	   75%-gray
	   88%-gray
	   12%-gray-color			;next several lines are new for color
	   25%-gray-color
	   33%-gray-color
	   50%-gray-color
	   66%-gray-color
	   75%-gray-color
	   88%-gray-color
	   alu-transp
	   alu-max
	   alu-min
	   alu-avg
	   alu-add
	   alu-sub
	   alu-adds
	   alu-subc
	   alu-back
	   black
	   white
	   red
	   green
	   blue
	   yellow
	   magenta
	   cyan
	   orange
	   blue-green
	   pink
	   purple
	   red-purple
	   light-brown
	   dark-green
	   dark-blue
	   dark-brown				;previous lines new for color
	   add-system-key
	   add-terminal-key
	   add-to-system-menu-column
	   add-typeout-item-type
	   add-window-type
	   adjust-by-interval
	   alias-for-inferiors-mixin
	   all-the-screens
	   alu-and
	   alu-andca
	   alu-ior
	   alu-seta
	   alu-setz
	   alu-xor
	   autoexposing-more-mixin
	   await-user-typeahead
	   background-color
	   basic-choose-variable-values
	   basic-frame
	   basic-mouse-sensitive-items
	   basic-multiple-choice
	   basic-typeout-window
	   baseline
	   baseline-adj
	   bit-array
	   bitblt-blinker
	   bitmap-mouse-pathname
	   black-on-white
	   blink
	   blinker
	   blinker-deselected-visibility
	   blinker-list
	   blinker-set-visibility
	   blinker-visibility
	   bordered-constraint-frame
	   bordered-constraint-frame-with-shared-io-buffer
	   borders
	   borders-mixin
	   bottom-box-label-mixin
	   bottom-margin-size
	   box-blinker
	   box-label-mixin
	   careful-notify
	   centered-label-mixin
	   char-aluf
	   char-width
	   character-blinker
	   choose-process-in-error
	   choose-variable-values
	   choose-variable-values-default-command-characters
	   choose-variable-values-find-continuation-items
	   choose-variable-values-keyword
	   choose-variable-values-keyword-function
	   choose-variable-values-pane
	   choose-variable-values-process-message
	   choose-variable-values-window
	   close-all-servers
	   command-characters
	   complement-bow-mode
	   constraint-frame
	   constraint-frame-with-shared-io-buffer
	   constraints
	   continuous-repeat-delay
	   current-font
	   current-item
	   current-item-mixin
	   cursor-x
	   cursor-y
	   deexposed-typeout-action
	   def-beep-type
	   default-beep
	   default-border-size
	   default-screen
	   default-window-types-item-list
	   deferred-notifications
	   define-mouse-char-mapping
	   defwindow-resource
	   delay-notification-mixin
	   delayed-redisplay-label-mixin
	   delaying-screen-management
	   delete-from-system-menu-column
	   describe-servers
	   deselect-and-maybe-bury-window
	   deselected-visibility
	   display-font
	   displayed-items-text-scroll-window
	   do-sound
	   doorbell
	   doplist
	   draw-char
	   draw-char-down
	   draw-char-up
	   draw-rectangle-inside-clipped
	   draw-rectangular-border
	   dynamic-item-list-mixin
	   edit-screen
	   erase-aluf
	   essential-activate
	   essential-expose
	   essential-mouse
	   essential-scroll-mouse-mixin
	   essential-set-edges
	   essential-window
	   essential-window-with-typeout-mixin
	   essential-window-with-typeout-mixin-typeout-window
	   expand-window
	   expose-window-near
	   exposed-inferiors
	   exposed-p
	   find-process-in-error
	   find-window-of-flavor
	   flags
	   flashy-margin-scrolling-mixin
	   flashy-scrolling-mixin
	   flush-full-screen-borders
	   follow-p
	   font-baseline
	   font-blinker-height
	   font-blinker-width
	   font-char-height
	   font-char-min-raster-width
	   font-char-width
	   font-char-width-table
	   font-chars-exist-table
	   font-evaluate
	   font-fill-pointer
	   font-indexing-table
	   font-left-kern-table
	   font-map
	   font-name
	   font-raster-height
	   font-raster-width
	   font-rasters-per-word
	   font-words-per-char
	   foreground-color
	   frame-forwarding-mixin
	   full-screen-hack-mixin
	   function-text-scroll-window
	   get-visibility-of-all-sheets-blinkers
	   get-window-edge-alist
	   gray-deexposed-right-mixin
	   gray-deexposed-wrong-mixin
	   half-period
	   height
	   highlighted-items
	   hollow-rectangular-blinker
	   hysteresis
	   hysteretic-window-mixin
	   ibeam-blinker
	   idle-lisp-listener
	   inferiors
	   inferiors-not-in-select-menu-mixin
	   initial-lisp-listener
	   initial-repeat-delay
	   initialize-multiple-move-blinker
	   initially-invisible-mixin
	   intrinsic-no-more-mixin
	   invisible-to-mouse-p
	   io-buffer
	   io-buffer-clear
	   io-buffer-empty-p
	   io-buffer-full-p
	   io-buffer-get
	   io-buffer-input-function
	   io-buffer-input-pointer
	   io-buffer-last-input-process
	   io-buffer-last-output-process
	   io-buffer-output-function
	   io-buffer-output-pointer
	   io-buffer-plist
	   io-buffer-push
	   io-buffer-put
	   io-buffer-record
	   io-buffer-record-pointer
	   io-buffer-size
	   io-buffer-state
	   io-buffer-unget
	   item-blinker
	   items
	   kbd-asynchronous-intercept-character
	   kbd-char-typed-p
	   kbd-default-output-function
	   kbd-global-asynchronous-characters
	   kbd-intercept-abort
	   kbd-intercept-abort-all
	   kbd-intercept-break
	   kbd-intercept-error-break
	   kbd-intercepted-characters
	   kbd-io-buffer-get
	   kbd-mouse-buttons-mixin
	   kbd-snarf-input
	   kbd-standard-asynchronous-characters
	   kbd-standard-intercepted-characters
	   kbd-sys-1
	   kbd-tyi-hook
	   kbd-wait-for-input-or-deexposure
	   kbd-wait-for-input-with-timeout
	   key-state
	   keypad-in-application-mode-p
	   label-mixin
	   label-needs-updating
	   last-who-line-process
	   left-margin-size
	   line-area-mouse-sensitive-text-scroll-mixin
	   line-area-text-scroll-mixin
	   line-height
	   line-truncating-mixin
	   lisp-interactor
	   listener-mixin
	   locations-per-line
	   lock
	   lock-count
	   lock-sheet
	   magnifying-blinker
	   main-screen
	   make-blinker
	   make-default-io-buffer
	   make-io-buffer
	   make-sheet-bit-array
	   map-over-exposed-sheet
	   map-over-exposed-sheets
	   map-over-sheet
	   map-over-sheets
	   margin-choice-mixin
	   margin-choices
	   margin-region-area
	   margin-region-bottom
	   margin-region-function
	   margin-region-left
	   margin-region-margin
	   margin-region-mixin
	   margin-region-right
	   margin-region-size
	   margin-region-top
	   margin-scroll-mixin
	   menu-golden-ratio
	   menu-item-string
	   merge-shift-keys
	   minimum-window
	   more-processing-global-enable
	   more-vpos
	   mouse-blinker
	   mouse-blinker-mixin
	   mouse-bounce-time
	   mouse-box-blinker
	   mouse-box-stay-inside-blinker
	   mouse-button-encode
	   mouse-buttons
	   mouse-call-system-menu
	   mouse-character-blinker
	   mouse-character-button-encode
	   mouse-confirm
	   mouse-default-handler
	   mouse-define-blinker-type
	   mouse-discard-clickahead
	   mouse-double-click-time
	   mouse-fast-motion-bitmap-time
	   mouse-fast-motion-cross-size
	   mouse-fast-motion-cross-time
	   mouse-fast-motion-speed
	   mouse-fast-track-bitmap-mouse-p
	   mouse-get-blinker
	   mouse-glyph-thin-up-arrow
	   mouse-glyph-thin-right-arrow
	   mouse-glyph-thin-down-arrow
	   mouse-glyph-thin-left-arrow
	   mouse-glyph-thin-up-down-arrow
	   mouse-glyph-thin-left-right-arrow
	   mouse-glyph-north-west-arrow
	   mouse-glyph-thin-cross
	   mouse-glyph-thick-up-arrow
	   mouse-glyph-thick-right-arrow
	   mouse-glyph-thick-down-arrow
	   mouse-glyph-thick-left-arrow
	   mouse-glyph-thick-up-down-arrow
	   mouse-glyph-paragraph
	   mouse-glyph-upper-left-corner
	   mouse-glyph-lower-right-corner
	   mouse-glyph-hourglass
	   mouse-glyph-circle-plus
	   mouse-glyph-paint-brush
	   mouse-glyph-scissor
	   mouse-glyph-trident
	   mouse-glyph-north-east-arrow
	   mouse-glyph-circle-x
	   mouse-glyph-large-right-triangle-pointer
	   mouse-glyph-medium-right-triangle-pointer
	   mouse-glyph-small-right-triangle-pointer
	   mouse-glyph-block-up-arrow
	   mouse-glyph-small-diamond
	   mouse-glyph-block-down-arrow
	   mouse-glyph-hollow-box-pointer
	   mouse-glyph-solid-box-pointer
	   mouse-glyph-hollow-circle-pointer
	   mouse-glyph-solid-circle-pointer
	   mouse-glyph-thick-hollow-cross
	   mouse-glyph-block-letter-t
	   mouse-glyph-hand-pointing-left
	   mouse-glyph-double-up-arrow
	   mouse-glyph-hollow-arc-pointer
	   mouse-glyph-solid-arc-pointer
	   mouse-glyph-spline-pointer
	   mouse-glyph-medium-diamond
	   mouse-glyph-hollow-triangle-pointer
	   mouse-glyph-solid-triangle-pointer
	   mouse-glyph-curtain
	   mouse-glyph-scale
	   mouse-glyph-6-3-arc-pointer
	   mouse-glyph-9-6-arc-pointer
	   mouse-glyph-3-12-arc-pointer
	   mouse-glyph-12-9-arc-pointer
	   mouse-glyph-ruler
	   mouse-glyph-polyline
	   mouse-glyph-double-up-arrow-lettered-d
	   mouse-glyph-thick-up-arrow-lettered-d
	   mouse-glyph-thick-line-pointer
	   mouse-glyph-question-mark
	   mouse-glyph-thin-hollow-cross
	   mouse-glyph-eye-glasses
	   mouse-glyph-thin-hollow-plus
	   mouse-glyph-rectangle-dots
	   mouse-glyph-west-rat-on-bottom
	   mouse-glyph-west-rat-on-top
	   mouse-glyph-north-rat-on-left
	   mouse-glyph-north-rat-on-right
	   mouse-glyph-east-rat-on-bottom
	   mouse-glyph-east-rat-on-top
	   mouse-glyph-south-rat-on-left
	   mouse-glyph-south-rat-on-right
	   mouse-glyph-west-curly-rat-on-bottom
	   mouse-glyph-west-curly-rat-on-top
	   mouse-glyph-north-curly-rat-on-left
	   mouse-glyph-north-curly-rat-on-right
	   mouse-glyph-east-curly-rat-on-bottom
	   mouse-glyph-east-curly-rat-on-top
	   mouse-glyph-south-curly-rat-on-left
	   mouse-glyph-south-curly-rat-on-right
	   mouse-glyph-west-mouse-on-bottom
	   mouse-glyph-west-mouse-on-top
	   mouse-glyph-north-mouse-on-left
	   mouse-glyph-north-mouse-on-right
	   mouse-glyph-east-mouse-on-bottom
	   mouse-glyph-east-mouse-on-top
	   mouse-glyph-south-mouse-on-left
	   mouse-glyph-south-mouse-on-right
	   mouse-glyph-small-dot
	   mouse-glyph-thick-cross
	   mouse-glyph-small-solid-circle
	   mouse-glyph-medium-solid-circle
	   mouse-glyph-hollow-circle
	   mouse-glyph-hollow-circle-minus
	   mouse-glyph-hollow-circle-plus
	   mouse-glyph-short-thin-down-border-arrow
	   mouse-glyph-short-thin-down-arrow
	   mouse-glyph-short-thin-up-border-arrow
	   mouse-glyph-short-thin-up-arrow
	   mouse-glyph-small-up-triangle
	   mouse-glyph-small-down-triangle
	   mouse-handedness
	   mouse-hollow-rectangular-blinker
	   mouse-input
	   mouse-last-buttons
	   mouse-last-buttons-time
	   mouse-last-x
	   mouse-last-y
	   mouse-process
	   mouse-rectangular-blinker
	   mouse-save-image
	   mouse-select
	   mouse-sensitive-item
	   mouse-sensitive-text-scroll-window
	   mouse-sensitive-text-scroll-window-without-click
	   mouse-set-blinker
	   mouse-set-blinker-cursorpos
	   mouse-set-blinker-definition
	   mouse-set-sheet
	   mouse-set-sheet-then-call
	   mouse-set-window-position
	   mouse-set-window-size
	   mouse-sheet
	   mouse-specify-rectangle
	   mouse-speed
	   mouse-standard-blinker
	   mouse-wait
	   mouse-wakeup
	   mouse-warp
	   mouse-window
	   sys:mouse-x
	   sys:mouse-y
	   mouse-y-or-n-p
	   multiple-choice
	   multiple-choose
	   multiple-move-blinker
	   name
	   no-screen-managing-mixin
	   noise
	   not-externally-selectable-mixin
	   notification-mixin
	   notify
	   number-of-who-line-documentation-lines
	   old-screen-array
	   open-all-sheets-blinkers
	   open-blinker
	   pane-no-mouse-select-mixin
	   pending-notifications
	   phase
	   pop-up-finger-window
	   pop-up-text-window
	   preemptable-read-any-tyi-mixin
	   prepare-sheet
	   preserve-substitute-status
	   previously-selected-windows
	   print-notifications
	   priority
	   process-mixin
	   process-typeahead
	   read-any
	   read-any-no-hang
	   read-bit-array-file
	   read-list
	   read-mouse-or-kbd
	   read-mouse-or-kbd-no-hang
	   rectangular-blinker
	   remap-mouse
	   remove-beep-type
	   remove-system-key
	   remove-terminal-key
	   reset-on-output-hold-flag-mixin
	   reset-sound
	   restore-mouse-map
	   restored-bits-p
	   reverse-character-blinker
	   right-margin-size
	   rotate-180
	   rotate-270
	   rotate-90
	   rubout-handler
	   rubout-handler-alpha-char-p
	   screen
	   screen-array
	   screen-manage-update-permitted-windows
	   screen-manager-screen-image
	   scroll-bar-mixin
	   scroll-bar-mode
	   scroll-interpret-entry
	   scroll-item-component-items
	   scroll-item-leader-offset
	   scroll-item-line-sensitivity
	   scroll-item-mouse-items
	   scroll-item-plist
	   scroll-item-size
	   scroll-maintain-list
	   scroll-maintain-list-unordered
	   scroll-maintain-list-update-states
	   scroll-mouse-mixin
	   scroll-parse-item
	   scroll-pixel-increment
	   scroll-string-item-with-embedded-newlines
	   scroll-stuff-on-off-mixin
	   scroll-window
	   scroll-window-with-typeout-mixin
	   select-mixin
	   select-or-create-window-of-flavor
	   selected-io-buffer
	   selected-window
	   selection-substitute
	   server-desc-host-name
	   set-number-of-who-line-documentation-lines
	   set-screen-standard-font
	   set-standard-font
	   set-visibility-of-all-sheets-blinkers
	   setup-application-mode
	   setup-keyboard-keyclick
	   setup-keypad-mode
	   setup-mouse-left-handed
	   setup-mouse-right-handed
	   shadow-borders-mixin
	   sheet
	   sheet-area
	   sheet-backspace-not-overprinting-flag
	   sheet-baseline
	   sheet-baseline-adj
	   sheet-bit-array
	   sheet-blinker-list
	   sheet-bottom-margin-size
	   sheet-bounds-within-sheet-p
	   sheet-calculate-offsets
	   sheet-can-get-lock
	   sheet-char-aluf
	   sheet-char-width
	   sheet-clear
	   sheet-clear-eof
	   sheet-clear-eol
	   sheet-compute-motion
	   sheet-contains-sheet-point-p
	   sheet-cr-not-newline-flag
	   sheet-current-font
	   sheet-cursor-x
	   sheet-cursor-y
	   sheet-deexposed-typein-notify
	   sheet-end-of-page-flag
	   sheet-end-page-flag
	   sheet-erase-aluf
	   sheet-exposed-inferiors
	   sheet-exposed-p
	   sheet-following-blinker
	   sheet-font-map
	   sheet-force-access
	   sheet-get-screen
	   sheet-height
	   sheet-inferiors
	   sheet-inside-bottom
	   sheet-inside-height
	   sheet-inside-left
	   sheet-inside-right
	   sheet-inside-top
	   sheet-inside-width
	   sheet-left-margin-size
	   sheet-line-height
	   sheet-line-no
	   sheet-line-out
	   sheet-me-or-my-kid-p
	   sheet-menu-abort-on-deexpose
	   sheet-menu-command-menu
	   sheet-menu-dynamic
	   sheet-menu-highlighting
	   sheet-menu-multicolumn
	   sheet-menu-pop-up
	   sheet-menu-permanent
	   sheet-more-flag
	   sheet-more-handler
	   sheet-number-of-inside-lines
	   sheet-output-hold-flag
	   sheet-overlaps-edges-p
	   sheet-overlaps-p
	   sheet-overlaps-sheet-p
	   sheet-read-cursorpos
	   sheet-right-margin-character-flag
	   sheet-right-margin-size
	   sheet-screen-array
	   sheet-set-cursorpos
	   sheet-set-font
	   sheet-string-length
	   sheet-string-out
	   sheet-superior
	   sheet-tab-nchars
	   sheet-tab-width
	   sheet-top-margin-size
	   sheet-truncate-line-out-flag
	   sheet-tyo
	   sheet-width
	   sheet-within-p
	   sheet-within-sheet-p
	   sheet-x-offset
	   sheet-y-offset
	   show-bit-array
	   show-partially-visible-mixin
	   simple-beep
	   spline
	   split-screen-via-menus-setup-window
	   stay-inside-blinker-mixin
	   stream-mixin
	   superior
	   temporary-bit-array
	   temporary-choose-variable-values-window
	   temporary-multiple-choice-window
	   temporary-shadow-borders-window-mixin
	   temporary-window-mixin
	   temporary-windows-locked
	   text-scroll-window
	   text-scroll-window-empty-gray-hack
	   text-scroll-window-typeout-mixin
	   time-stamp
	   time-until-blink
	   tone
	   tone-frequency
	   top-box-label-mixin
	   top-item
	   top-label-mixin
	   top-margin-size
	   truncating-pop-up-text-window
	   truncating-pop-up-text-window-with-reset
	   truncating-window
	   turn-off-all-sheets-blinkers
	   turn-off-sheet-blinkers
	   turn-on-sheet-blinkers
	   typeout-item-bottom
	   typeout-item-item
	   typeout-item-left
	   typeout-item-right
	   typeout-item-top
	   typeout-item-type
	   typeout-window
	   typeout-window-with-mouse-sensitive-items
	   unread-any
	   value-tab
	   visibility
	   white-on-black
	   who-line-clobbered
	   who-line-file-state-sheet
	   who-line-mouse-grabbed-documentation
	   who-line-process
	   who-line-run-state
	   who-line-screen
	   width
	   window-call
	   window-hacking-menu-mixin
	   window-mouse-call
	   window-owning-mouse
	   window-resource-names
	   window-under-mouse
	   window-with-typeout-mixin
	   with-blinker-ready
	   with-clipping-rectangle
	   with-mouse-grabbed
	   with-mouse-usurped
	   with-selection-substitute
	   with-sheet-deexposed
	   without-screen-management
	   write-bit-array-file
	   write-keyboard
	   x-offset
	   y-offset
	   x-pos
	   y-pos))


;; these symbols should be imported by the mac package

;; Roughly, the following symbols are those needed to support the
;; 'classic' Lisp Machine TV system.
(defparameter *mac-support-symbols*
  '(*cold-load-streams-screen-selected-p*
    *default-Mac-window-height*
    *default-Mac-window-width*
    *dont-clip-at-the-margins*
    *Explorer-to-Mac-char-code-map*
    *ignore-commands-for-the-mac*
    *mac*
    *mac-keyboard-p*
    *mac-system-p*
    ;; dab 8/24/88
    *Mac-resident-Explorer-screens*
    ;; dab 8/24/88
    *undisplaced-Mac-window-arrays*
    *window-system-mouse-on-the-mac*
    ;; dab 08-24-88 DAB
    dump-draw-char-cache
    lispm-shift-bit
    lispm-greek-bit
    lispm-top-bit
    lispm-capslock-bit
    lispm-control-bit
    lispm-meta-bit
    lispm-super-bit
    lispm-hyper-bit
    lispm-altlock-bit
    lispm-modelock-bit
    lispm-repeat-bit

    Mac-CONTROL-bit
    Mac-OPTION-bit
    Mac-CAPSLOCK-bit
    Mac-SHIFT-bit
    Mac-COMMAND-bit
    Mac-MOUSE-bit
    Mac-AUTOKEY-bit
    Mac-Window-Activate-bit
    ;; dab 8/24/88
    mac-explorer-screen-ID-for-screen-being-created
    mac-extended-kbd-descriptor
    mac-kbd-modifier-table
    mac-kbd-modifier-table-zmacs-mode
    mac-screen
    ;; dab 8/24/88
    Mac-screen-for-printer
    mac-standard-kbd-descriptor
    ;; dab 8/24/88
    not-visible-p
    kbd-mac-table

    ;; functions
    activate-mac-window
    after-tv-initialized
    analyze-last-button
    deactivate-mac-screen
    deactivate-mac-window
    define-mac-resident-exp-screen
    deselect-cold-load-streams-screen
    give-mouse-ownership-to-the-explorer
    kbd-convert-mac
    kbd-make-mac-table
    lispm-or-mac-mouse-wakeup
    mac-consider-mouse
    mac-key
    mac-screen-p
    mac-system-p
    mac-window-p
    make-a-Mac-resident-Explorer-screen
    ;; dab 8/24/88
    make-explorer-screen
    redirect-drawing-of-window-and-inferiors
    ;; 10/18/88
    remember-bit-array
    remember-this-screens-last-selected-window
    select-cold-load-streams-screen
    send-adjust-bit-array-maybe
    send-draw-char
    send-draw-line
    send-draw-point
    send-draw-rectangle
    send-draw-string
    send-drawcircle
    send-drawhollowcircle
    send-drawhollowrectangle
    send-draw-filled-polygon
    send-select-window
    select-a-screen
    si-bitblt))


;; (import tv:*mac-support-symbols* 'mac)
